all: ejemploPolimorfismo0.cpp
	g++ -O3 ejemploPolimorfismo0.cpp -o ejemploPolimorfismo0
	g++ -O3 ejemploPolimorfismo1.cpp -o ejemploPolimorfismo1
	g++ -O3 ejemploPolimorfismo2.cpp -o ejemploPolimorfismo2
	g++ -O3 ejemploPolimorfismo3.cpp -o ejemploPolimorfismo3
	g++ -O3 ejemploPolimorfismo4.cpp -o ejemploPolimorfismo4

debug: ejemploPolimorfismo0.cpp
	g++ -g ejemploPolimorfismo0.cpp -o ejemploPolimorfismo0
	g++ -g ejemploPolimorfismo1.cpp -o ejemploPolimorfismo1
	g++ -g ejemploPolimorfismo2.cpp -o ejemploPolimorfismo2
	g++ -g ejemploPolimorfismo3.cpp -o ejemploPolimorfismo3
	g++ -g ejemploPolimorfismo4.cpp -o ejemploPolimorfismo4

clean:
	rm ejemploPolimorfismo0
	rm ejemploPolimorfismo1
	rm ejemploPolimorfismo2
	rm ejemploPolimorfismo3
	rm ejemploPolimorfismo4