all: estrategiaplantilla.cpp
	g++ -O3 estrategiaplantilla.cpp -o estrategiaplantilla
	g++ -O3 estructura.cpp -o estructura
	g++ -O3 estructura1.cpp -o estructura1
	g++ -O3 estructura2.cpp -o estructura2


debug: estrategiaplantilla.cpp
	g++ -g estrategiaplantilla.cpp -o estrategiaplantilla
	g++ -g estructura.cpp -o estructura
	g++ -g estructura1.cpp -o estructura1
	g++ -g estructura2.cpp -o estructura2

clean:
	rm estrategiaplantilla
	rm estructura
	rm estructura1
	rm estructura2